package com.microservice.film_service.film_service.model;

public enum Genre {
    ACTION,
    ADULT,
    ADVENTURE,
    ANIME,
    ANIMATION,
    CHILDREN,
    CRIME,
    COMEDY,
    DOCUMENTARY,
    DRAMA,
    EDUCATION,
    EROTIC,
    FAITH_AND_SPIRITUALITY,
    FAMILY,
    FANTASY,
    FOOD,
    HORROR,
    INDEPENDENT,
    INSTRUCTIONAL,
    LIVE_PERFORMANCE,
    MUSIC_PERFORMANCE,
    MUSICAL,
    MYSTERY,
    REALITY,
    ROMANCE,
    SCIENCE_FICTION,
    SCI_FI,
    SPORTS,
    THRILLER,
    VARIETY_TALKSHOW,
    WESTERN,
    WAR,
    MISCELLANEOUS,
    IMAX
}
